[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
echo = "251VpQ2e7acPSqM4m7DRoUMpfX9mEtFXHjbYRx2C5JGX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/johnnycage/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
